server:
  port: 8081 # Graph Service will run on port 8081

spring:
  application:
    name: graph-service

  # Neo4j connection settings
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password # In production, we will get this from environment variables

  data:
    neo4j:
      database: neo4j

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: graph-service-group # Вот этого поля не хватало
      auto-offset-reset: earliest
      # Важно: ключи - строки, значения - байты (Protobuf)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

# Logging configuration to see our gRPC requests
logging:
  level:
    root: INFO
    com.deeplink: DEBUG